ignore: # Ignore codecov for currently unused files
  - "app/Events/*.php"
  - "app/Listeners/*.php"
  - "app/Http/Controllers/ProfileController.php"
  - "app/Http/Controllers/LaTeXController.php"
  - "app/Http/Requests/ProfileUpdateRequest.php"
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5
comment:
     layout: "condensed_header, condensed_files, condensed_footer"
     require_changes: true
     hide_project_coverage: true
