name: test
on:
  pull_request:
  release:
    types: [published]
  push:
    tags: "*"
    branches: "*"
  workflow_dispatch:

jobs:
  Test:
    if: ${{ !contains(github.event.head_commit.message, '[skip test]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@2.30.4
        with:
          php-version: "8.3"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Run composer install
        run: composer install

      - name: Run pnpm install
        run: pnpm install

      - name: Run tests
        run: php artisan test # run unit tests only as I failed to figure out how to fix feature tests
