name: Build Worker Image

on:
  push:
    paths: ["build/worker/**"]
  schedule:
    - cron: '30 2 * * 1'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Docker setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata action
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/worker-base
          tags: |
            type=ref,event=branch
            type=raw,value=latest
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=sha,enable=true,priority=100,prefix=,suffix=,format=short

      - name: Publish images
        uses: docker/build-push-action@v5
        with:
          context: ./build/worker
          file: ./build/worker/Dockerfile.base
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          push: true
